name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - 'auth/**'

defaults:
  run:
    working-directory: auth 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
        env:
          PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: auth/dist # The folder the action should deploy.
          target-folder: auth/latest/
